camerasettings = {
    [0] = { -- This has to be an ID, in INT, so only 0,1,2,3, etc.
        name = "Follow - Near", -- Name.
        isbumpercamera = false, -- if it is a bumper camera (hood camera), if this is enabled, all other factors will be disconsidered.
        isfpvcamera = false, -- if it is a first person view camera, if this is enabled, all other factors will be disconsidered.
        interpolationfactor = 0.01625, -- The main attribute of the camera, constrols the speed of interpolation, consequently how close the camera is from the car
                                       -- The higher it is, the closer it will be, the lesser it is, the further. Be careful increasing past default value, as it may cause jitter.
        zheight = 0.5,  -- how high the camera is in relation to the vehicle roof or highest point.
        zheightbike = 0.55,  -- how high the camera is in relation to the vehicle roof or highest point (on bikes).
        basefov = 65, -- Base FOV
        joltintensity = 0.66, -- Intensity of the jolt shake effect when landing of a intense airtime.
        dynamicfovgainfactor = 20.25, -- Base fov for dynamic fov calculation, the more, more fov gained based on your speed.
        basepitch = 0.675, -- Base offset for the camera pitch when idling/stoppd, the more, the upwards the camera will look, the less, the more downwards.
        coastpitch = 0.85, -- How much the camera looks upwards when not accelerating, nor braking, the more, the upwards the camera will look, the less, the more downwards.
        accpitch = 1.0, -- How much the camera looks upwards when accelerating, the more, the upwards the camera will look, the less, the more downwards.
        brakingpitch = 0.525, -- How much the camera looks downwards when braking, the more, the upwards the camera will look, the less, the more downwards.
        brakingforwardfactor = 2.25, -- How much the camera goes forward while braking, the more, the closer, the less, the further.
        brakinganimationspeed = 0.00544375, -- How fast the camera goes forward when braking the more, the faster, the less, the slower.
        brakinganimationreturnrate = 11, -- How fast the camera returns to center when releasing the brakes the more, the faster, the less, the slower.
        useangularvelocity = false, -- Considers angular velocity when turning regurlaly, and translates that to the camera, use this for "agressive" transitions.
        useangularvelocityondriftonly = true, -- Considers angular velocity when turning regurlaly, and translates that to the camera only when drifting, use this for "agressive" transitions.
        useinvertedangularvelocity = false, -- Inverts the angular velocity, good if using only drifting, without auto drift angle
        driftingbackwardsfactor = 0.05, -- How much the camera goes backward while drifting, the more, the further, the less, the closer.
        driftinganimationspeed = 0.024125, -- How fast the camera turns towards the drift angle when drifting, the more, the faster, the less, the slower.
        driftinganimationreturnrate = 11, --  How fast the camera returns towards the neutral angle post drifting, the more, the faster, the less, the slower.
        nitrousbackwardsfactor = 10.0, -- How much the camera goes backward while using nitrous, the more, the further, the less, the closer.
        nitrousanimationspeed = 0.006, -- How fast the camera goes backwars when using nitrous the more, the faster, the less, the slower.
        nitrousanimationreturnrate = 8, -- How fast the camera returns to center when the nitrous ends the more, the faster, the less, the slower.
        useautodriftangle = true, -- Automatically figures the best way to keep with the car when drifting, reccomend to be enabled, if enabled, manual drift angle controls are disabled.
        autodriftangletarget = 35, -- The target slip angle of the camera, meaning until how much it will turn, edit this to increase or decrease the angle the camera auto locks.
        autodriftvisibilityfactor = 1.5, -- Increase this value for more focus on the road when drifting, decrease it for more focus on the car when drifting.
                                        -- Depending on your camera settings, sometimes you might need to use this value as negative, so for example, on the medium distance camera below, we use it at -1.5 to keep a similar effect to here.
        mincameradriftangle = 0.0, -- The minimal drift angle that the camera will start, ideally, this should never be changed, however, the more, the more visbility on the corner when
                                  -- drifiting, the less, the fewer visibility of the corner, and more of the car.
        maxcameradriftangle = 1.75, -- The Max drift angle that the camera will turn into, the more, the more visbility on the corner when drifiting,
                                  -- the less, the fewer visibility of the corner, and more of the car.
        mindriftangle = 12.5, -- The minimal drift angle specified for the camera start to shift the camera drift angle, 
                             -- meaning the camera angle will only start going to the specified max if your drifting angle is more than the one specified here.
        maxdriftangle = 65, -- The Maximum drift angle specified for the camera finish to shift the camera drift angle, meaning the camera angle will reach it's peak
                             -- When at the angle specified here.
        enabledriftcamerashake = true, -- Enables a shaking effect when drifiting, similar to popular modern arcade racing games.
        driftcamerashakefakespeed = 175, -- Simulates a shaking effect at a fake speed, given in km/h, the more, the stronger the shake, the less, the weaker.
        driftcamerashakewavefrequency = 32.5, -- Simulates the wave used for the shaking effect when drifting, the less the longer the shake (will go and down higher/lower), the more, the smaller.
        enablehighspeedcamerashake = true, -- Enables a shaking effect when at high speeds.
        highspeedcamerashakemagnitude = 0.00425, -- The magnitude (intensity), of the camera shake, the more, the stronger, the less, the weaker.
                                                 -- This will also influenciate the drift camera intensity.
        highspeedcamerashakefrequency = 50, -- Simulates the wave used for the shaking effect, the less the longer the shake (will go and down higher/lower), the more, the smaller.
        orbitcamspeed = 30, -- The speed of the orbitcam, the more, the faster, the less, the slower.
        orbitcamsensitivity= 0.60, -- The sensitivity of the orbitcam, the more, the faster, the less, the slower.
        orbitcamresettime= 350, -- The time that the player needs to not have a mouse input in order for the orbit cam to reset to default, given in MS, the more, the larger, the less, the smaller.
    },
    [1] = {
        name = "Follow - Medium",
        isbumpercamera = false,
        isfpvcamera = false,
        interpolationfactor = 0.01421875,
        zheight = 0.6,
        zheightbike = 0.55,
        basefov = 65,
        joltintensity = 0.66,
        dynamicfovgainfactor = 20.25,
        basepitch = 0.675,
        coastpitch = 0.85,
        accpitch = 1.0,
        brakingpitch = 0.525,
        brakingforwardfactor = 2.25,
        brakinganimationspeed = 0.00544375,
        brakinganimationreturnrate = 11,
        useangularvelocity = false,
        useangularvelocityondriftonly = true,
        useinvertedangularvelocity = true,
        driftingbackwardsfactor = 0.3,
        driftinganimationspeed = 0.024125,
        driftinganimationreturnrate = 11,
        nitrousbackwardsfactor = 10.0,
        nitrousanimationspeed = 0.006,
        nitrousanimationreturnrate = 8, 
        useautodriftangle = true,
        autodriftangletarget = 35,
        autodriftvisibilityfactor = -1.5,
        mincameradriftangle = 0.0,
        maxcameradriftangle = 1.75,
        mindriftangle = 12.5,
        maxdriftangle = 65,
        enabledriftcamerashake = false,
        driftcamerashakefakespeed = 175,
        driftcamerashakewavefrequency = 32.5,
        enablehighspeedcamerashake = true,
        highspeedcamerashakemagnitude = 0.00425,
        highspeedcamerashakefrequency = 50,
        orbitcamspeed = 30,
        orbitcamsensitivity= 0.60,
        orbitcamresettime= 350,
    },
    [2] = {
        name = "Follow - Far",
        isbumpercamera = false,
        isfpvcamera = false,
        interpolationfactor = 0.012,
        zheight = 0.65,
        zheightbike = 0.55,
        basefov = 65,
        joltintensity = 0.66,
        dynamicfovgainfactor = 20.25,
        basepitch = 0.675,
        coastpitch = 0.85,
        accpitch = 1.0,
        brakingpitch = 0.525,
        brakingforwardfactor = 2.25,
        brakinganimationspeed = 0.00544375,
        brakinganimationreturnrate = 11,
        useautodriftangle = true,
        autodriftangletarget = 35,
        autodriftvisibilityfactor = -1.75,
        useangularvelocity = false,
        useangularvelocityondriftonly = true,
        useinvertedangularvelocity = true,
        driftingbackwardsfactor = 0.3,
        driftinganimationspeed = 0.024125,
        driftinganimationreturnrate = 11,
        nitrousbackwardsfactor = 10.0,
        nitrousanimationspeed = 0.006,
        nitrousanimationreturnrate = 8, 
        mincameradriftangle = 0.0,
        maxcameradriftangle = 1.75,
        mindriftangle = 12.5,
        maxdriftangle = 65,
        enabledriftcamerashake = false,
        driftcamerashakefakespeed = 175,
        driftcamerashakewavefrequency = 32.5,
        enablehighspeedcamerashake = true,
        highspeedcamerashakemagnitude = 0.00425,
        highspeedcamerashakefrequency = 50,
        orbitcamspeed = 30,
        orbitcamsensitivity= 0.60,
        orbitcamresettime= 350,
    },
    [3] = {
        name = "Hood",
        isbumpercamera = true,
        isfpvcamera = false,
        interpolationfactor = 0.01625,
        zheight = 0.425,
        zheightbike = 0.55,
        basefov = 65,
        joltintensity = 0.66,
        dynamicfovgainfactor = 20.25,
        basepitch = 0.675,
        coastpitch = 0.85,
        accpitch = 1.0,
        brakingpitch = 0.525,
        brakingforwardfactor = 2.25,
        brakinganimationspeed = 0.00544375,
        brakinganimationreturnrate = 11,
        useangularvelocity = false,
        useangularvelocityondriftonly = true,
        useinvertedangularvelocity = true,
        driftingbackwardsfactor = 0.3,
        driftinganimationspeed = 0.024125,
        driftinganimationreturnrate = 11,
        nitrousbackwardsfactor = 10.0,
        nitrousanimationspeed = 0.006,
        nitrousanimationreturnrate = 8, 
        useautodriftangle = true,
        autodriftangletarget = 35,
        autodriftvisibilityfactor = 1.5,
        mincameradriftangle = 0.0,
        maxcameradriftangle = 1.75,
        mindriftangle = 12.5,
        maxdriftangle = 65,
        enabledriftcamerashake = false,
        driftcamerashakefakespeed = 175,
        driftcamerashakewavefrequency = 32.5,
        enablehighspeedcamerashake = true,
        highspeedcamerashakemagnitude = 0.00425,
        highspeedcamerashakefrequency = 50,
        orbitcamspeed = 30,
        orbitcamsensitivity= 0.60,
        orbitcamresettime= 350,
    },
    [4] = {
        name = "FPV",
        isbumpercamera = false,
        isfpvcamera = true,
        interpolationfactor = 0.01625,
        zheight = 0.425,
        zheightbike = 0.55,
        basefov = 65,
        joltintensity = 0.66,
        dynamicfovgainfactor = 20.25,
        basepitch = 0.675,
        coastpitch = 0.85,
        accpitch = 1.0,
        brakingpitch = 0.525,
        brakingforwardfactor = 2.25,
        brakinganimationspeed = 0.00544375,
        brakinganimationreturnrate = 11,
        useangularvelocity = false,
        useangularvelocityondriftonly = true,
        useinvertedangularvelocity = true,
        driftingbackwardsfactor = 0.3,
        driftinganimationspeed = 0.024125,
        driftinganimationreturnrate = 11,
        nitrousbackwardsfactor = 10.0,
        nitrousanimationspeed = 0.006,
        nitrousanimationreturnrate = 8, 
        useautodriftangle = true,
        autodriftangletarget = 35,
        autodriftvisibilityfactor = 1.5,
        mincameradriftangle = 0.0,
        maxcameradriftangle = 1.75,
        mindriftangle = 12.5,
        maxdriftangle = 65,
        enabledriftcamerashake = false,
        driftcamerashakefakespeed = 175,
        driftcamerashakewavefrequency = 32.5,
        enablehighspeedcamerashake = true,
        highspeedcamerashakemagnitude = 0.00425,
        highspeedcamerashakefrequency = 50,
        orbitcamspeed = 30,
        orbitcamsensitivity= 0.60,
        orbitcamresettime= 350,
    }
}